//load game
export const LOAD_GAME = "LOAD_GAME";
export const LOAD_GAME_PENDING = "LOAD_GAME_PENDING";
export const LOAD_GAME_FULFILLED = "LOAD_GAME_FULFILLED";
export const LOAD_GAME_REJECTED = "LOAD_GAME_REJECTED";


//add game
export const ADD_GAME = "ADD_GAME";
export const ADD_GAME_PENDING = "ADD_GAME_PENDING";
export const ADD_GAME_FULFILLED = "ADD_GAME_FULFILLED";
export const ADD_GAME_REJECTED = "ADD_GAME_REJECTED";

//remove
export const REMOVE_GAME = "REMOVE_GAME";
export const REMOVE_GAME_PENDING = "REMOVE_GAME_PENDING";
export const REMOVE_GAME_FULFILLED = "REMOVE_GAME_FULFILLED";
export const REMOVE_GAME_REJECTED = "REMOVE_GAME_REJECTED";

//update
export const UPDATE_GAME ="UPDATE_GAME";
export const UPDATE_GAME_PENDING = "UPDATE_GAME_PENDING";
export const UPDATE_GAME_FULFILLED = "UPDATE_GAME_FULFILLED";
export const UPDATE_GAME_REJECTED = "UPDATE_GAME_REJECTED";

//get 
export const FETCH_GAME ="FETCH_GAME";
export const FETCH_GAME_PENDING = "FETCH_GAME_PENDING";
export const FETCH_GAME_FULFILLED = "FETCH_GAME_FULFILLED";
export const FETCH_GAME_REJECTED = "FETCH_GAME_REJECTED";
